gmtsar/CMakeLists.txt
gmtsar/csh/CMakeLists.txt

Running `make install` fails when the csh scripts from `gmtsar/csh/` are to be installed, because the install command assumes these scripts to be in `gmtsar/` instead of `gmtsar/csh/`.
This PR fixes it by moving the install command for csh scripts into `gmtsar/csh/CMakeLists.txt` and including this new file in `gmtsar/CMakeLists.txt`.
With this issue fixed, `make install` still fails due to some missing files:
- `gmtsar/csh/gmtsar_sharedir.csh` however there is `gmtsar/csh/gmtsar_sharedir.csh.in`
- and the following files which (I guess) have been removed from this repository some time ago:
```
p2p_ALOS.csh
p2p_ALOS2_SCAN_SLC.csh
p2p_ALOS2_SLC.csh
p2p_ALOS_SLC.csh
p2p_CSK.csh
p2p_CSK_SLC.csh
p2p_ENVI.csh
p2p_ENVI_SLC.csh
p2p_ERS.csh
p2p_RS2_SLC.csh
p2p_S1A_SLC.csh
p2p_S1A_TOPS.csh …
```

fixed path name for installing the csh scripts

---

preproc/S1A_preproc/src_tops/make_s1a_tops.c

It appears that the variables ii and t2 are used in an iteration to
find the index (ii) of the first orbit velocity entry that occurs at a
time (t2) after the burst time (t_brst). At the end of this iteration
t1 is the time of the last orbit velocity state prior to t_brst, and
the corresponding index is ii-1.
The code following this iteration interpolates vx, vy and vz for
t_brst. However, prior to the change in this commit, if one sets
t_brst to be t1, one would get vx, vy and vz associated with t2, and
vice versa.
I believe this is an error.
Thanks for your consideration.

I believe this commit corrects an orbit interpolation error.

---

gmtsar/csh/CMakeLists.txt

Hi, just a quick fix I ran into while compiling gmtsar :)
When gmtsar_sharedir.csh.in is configured, the resulting
gmtsar_sharedir.csh ends up in the current binary dir, which is not the
same as the current source dir when performing an out-of-tree build.

Fix out-of-tree cmake build

---

gmtsar/csh/snaphu.csh

I've modified the snaphu.csh code for SNAPHU to generate a connected component file after unwrapping. The filename is conncomp.grd.

Generate connected component file after unwrapping using snaphu.csh

---

gmtsar/csh/snaphu_interp.csh

I've modified the snaphu_interp.csh code for SNAPHU to generate a connected component file after unwrapping. The filename is conncomp.grd.

Generate connected component file after unwrapping using snaphu_interp.csh

---

preproc/S1A_preproc/src_tops/make_s1a_tops.c

For preprocessing valid S1A tiff files (large, but less than 4Gb), I ran into an issue with make_s1a_tops. The error code was "malloc(): corrupted top size. Aborted (core dumped)."  preproc failed. 
Based on a post in the forums, I fixed it by increasing the size of a make_s1a_tops variable in malloc() from 80 to 180, and then re-making GMTSAR.  The issue was resolved.  
Thanks to Yunfeng Tian for solving this issue two years ago.  Thought it would be good to fix it at the source.  
Forum post: http://gmt.soest.hawaii.edu/boards/6/topics/7057
System information: I am on Ubuntu 20.04, GMTSAR6.0, cloned only a few days ago

changing malloc 80 to malloc 180 for larger S1 arrays

---

gmtsar/csh/fetchOrbit.py

I've made some changes on the fetchOrbit.py since ESA Copernicus has changed again the download link on the XML of the scihub GNSS Copernicus website. I've also implemented these changes in ISCE2 (isce-framework/isce2#273). This PR is a reopen PR of https://github.com/gmtsar/gmtsar/pull/127.

Edited the fetchOrbit.py due to changes again on the orbit download link

---

gmtsar/csh/intf_batch.csh
gmtsar/csh/intf_batch_ALOS2_SCAN.csh
gmtsar/csh/intf_tops.csh
gmtsar/csh/merge_unwrap_geocode_tops.csh
gmtsar/csh/p2p_ALOS2_SCAN_SLC.csh
gmtsar/csh/p2p_ENVI.csh
gmtsar/csh/p2p_ERS.csh
gmtsar/csh/p2p_S1_TOPS.csh

As I'm generating InSAR maps, I've found out that some of the processing scripts don't incorporate the mask_water parameter which is generated by pop_config.csh. I've edited those scripts so they can accept either accept switch_land or mask_water parameter during processing.

Set some processing script to accept mask_water parameter

---

gmtsar/Makefile

I've edited this Makefile to include python scripts on the bin folder during execution of make install

Include python scripts during make install

---

gmtsar/csh/fetchOrbit.py

I've made some changes to fetchOrbit.py due to changes made by ESA once again based on the issue presented in #273 (comment). I've mirrored this PR from https://github.com/isce-framework/isce2/pull/282.
Hopefully, ESA would not change it again frantically.

Changes to line 155 of fetchOrbit.py

---

configure.ac

Last time I failed to install on my m1 Mac, I tried to install with docker, and the installation was easy on Ubuntu amd64, but the installation failed on Ubuntu arm64, gcc arm does not support -m64.

adding Linux arm64 support

---

gmtsar/csh/organize_files_tops.csh

These updates replace the former wgetasf alias command with the language from the ESA API system to automatically download precise orbit files for the given SAFE file names specified by the user. The logic has been updated to query the ESA database for a specific date of file and download that file, instead of querying the entire database for a single list of all files and finding the matching file on the list. I also updated the $orb variable to be $orbit. In addition, I updated the usage output to reflect these changes.

Replace wgetASF with ESA query for organize_files_tops

---

gmtsar/csh/organize_files_tops_linux.csh

LINUX version: These updates replace the former wgetasf alias command with the language from the ESA API system to automatically download precise orbit files for the given SAFE file names specified by the user. The logic has been updated to query the ESA database for a specific date of file and download that file, instead of querying the entire database for a single list of all files and finding the matching file on the list. I also updated the $orb variable to be $orbit. In addition, I updated the usage output to reflect these changes.

(Linux version) Replace wgetASF orbit query with ESA query organize_files_tops_linux.csh

---

gmtsar/csh/organize_files_tops.csh
gmtsar/csh/organize_files_tops_linux.csh

I replaced $SAT1 with $SAT0 in order to have the ESA query find and grab the correct satellite (S1A/S1B) orbit file.

Organize_files_tops Fixing Bug with satellite name for orbit files

---

gmtsar/csh/align_ALOS_SLC.csh
gmtsar/csh/align_batch_ALOS_SLC.csh

2 changes: fix typo PRM to PRF in align_ALOS_SLC.csh, and update name of LED files in align_batch_ALOS_SLC.csh.

Bug fixes for alignment with ALOS SLCs. 

---

gmtsar/SAT_baseline.c
gmtsar/lib_functions.h
gmtsar/make_gaussian_filter.c
gmtsar/phasediff.c
gmtsar/phasediff_get_topo_phase.c
gmtsar/phasefilt.c

Hard-coded filenames is evil for interoperability. The patch replaces these by optional command-line arguments. These changes are work well for PyGMTSAR and can be easily checked in just one click by running the example PyGMTSAR notebooks on Google Colab.

Fix printf issue and allow to redefine default filenames

---

gmtsar/csh/correct_insar_with_gnss.csh
gmtsar/csh/extract_one_time_series.csh

This changes the upsampling method in correct_insar_with_gnss.csh to using gmt grdsample instead of gmt surface. Also, there is a small edit to extract_one_time_series.csh that makes it more flexible when pulling information from the user-provided scene.tab file.

Update to correct_insar_with_gnss and extract_one_time_series

---

.github/workflows/gmtsar.yml

Add CI tests to check GMTSAR compilation and installation on Ubuntu-22.04, Ubuntu-20.04, Ubuntu-18.04, MacOS-12, MacOS-11. Also, the test downloads the example S1A_Stack_CPGF_T173.tar.gz and unpack and launch all the scripts for the complete SBAS processing. That's possible to add the test results badge on the main repository page. The test workflow starts on every commit and pull request to master branch. Note: Ubuntu-18.04 support will be removed on 1 Apr 2023.

Add CI test for GMTSAR

---

gmtsar/csh/merge_unwrap_geocode_tops.csh

When det_stitch is enabled: To avoid scenarios where the starting column of the swath is partially NaNs and partially valid data results in a partial gap in the merged swath (see below), the +n option in the grdcut strips away NaNs from the grd file and avoids the partial gap problem in the merged swath.

When det_stitch is enabled, in some scenarios, a partial gap could exist in the merged swath (merge_unwrap_geocode_tops.csh)

---

.github/workflows/gmtsar.yml
README.md

Update GMTSAR CI test and remove outdated Ubuntu 18 target (will be discontinued in the April). Add test badge on the main page.

Update CI test

---

Makefile
preproc/ALOS_preproc/ALOS_fbd2fbs/Makefile
preproc/ALOS_preproc/ALOS_fbd2fbs_SLC/Makefile
preproc/ALOS_preproc/ALOS_fbd2ss/Makefile
preproc/ALOS_preproc/ALOS_merge/Makefile
preproc/ALOS_preproc/ALOS_pre_process/Makefile
preproc/ALOS_preproc/ALOS_pre_process_SLC/Makefile
preproc/ALOS_preproc/ALOS_pre_process_SS/Makefile
preproc/CSK_preproc/src_raw/Makefile
preproc/CSK_preproc/src_slc/Makefile
preproc/ENVI_preproc/ASA_CAT/Makefile
preproc/ENVI_preproc/Dop_orbit/Makefile
preproc/ENVI_preproc/ENVI_decode/Makefile
preproc/ERS_preproc/ers_line_fixer/Makefile
preproc/ERS_preproc/read_data_file_ccrs/Makefile
preproc/ERS_preproc/read_data_file_dpaf/Makefile
preproc/ERS_preproc/read_sarleader_dpaf/Makefile
preproc/GF3_preproc/Makefile
preproc/GF3_preproc/src/Makefile
preproc/LT1_preproc/Makefile
preproc/LT1_preproc/src/Makefile
preproc/NSR_preproc/Makefile
preproc/NSR_preproc/src_slc/Makefile
preproc/RS2_preproc/src/Makefile
preproc/S1A_preproc/Makefile
preproc/S1A_preproc/lib/Makefile
preproc/S1A_preproc/src_orbit/Makefile
preproc/S1A_preproc/src_swath/Makefile
preproc/TSX_preproc/src/Makefile

Improve the clean and spotless targets to ensure that the git checkout is totally clean (including ignored file) after a call to
```
make spotless
```

Fix clean and spotless targets

---

Makefile

Do not set executable flag on files in `share/gmtsar` at installation time

Fix file permissions

---

configure.ac

-m32/-m64 are generally used only when doing multiarch builds; in a non-cross build there is no need for them, and they may be even not available.
gmtsar builds fine without them, hence drop them altogether.

Stop passing -m32/-m64 when building
